version: "2.0"
services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: "elasticsearch"
    ports:
      - 9200:9200
      - 9300:9300

  search_kb_product:
    image: cryptodraco/kiabi_product_suggestion:v0.0.1
    container_name: "search_kb_product"
    hostname: search_kb_product
    restart: always

    environment:
      - NUC=1 #environement de dev
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 5000:5000
