version: "2.0"
services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    networks:
      - docker-elk
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - docker-elk
    depends_on:
      - elasticsearch

networks:
  docker-elk:
    driver: bridge
